# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rekord < Formula
  desc "Record terminal workflows as structured session data"
  homepage "https://github.com/Omotolani98/rekord"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.2/rekord_0.1.2_darwin_amd64.tar.gz"
      sha256 "415858f2ab1250bad177e1d8f83cc6bd71b192f2b39c8168d573b0db1ffd34be"

      define_method(:install) do
        bin.install "rekord"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.2/rekord_0.1.2_darwin_arm64.tar.gz"
      sha256 "82d748c108d4e5b054a20c2a4e20c1a2d8d79ffdf6225ee840b130331975d580"

      define_method(:install) do
        bin.install "rekord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.2/rekord_0.1.2_linux_amd64.tar.gz"
      sha256 "a877b9482756852164cbe92e48cf741562fef6c45254e49b81f926953d0ed65d"
      define_method(:install) do
        bin.install "rekord"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.2/rekord_0.1.2_linux_arm64.tar.gz"
      sha256 "5bdb77214c6c25f30242d80afe2a6ee0725dedf8528fbf52300a63f126c2ba0e"
      define_method(:install) do
        bin.install "rekord"
      end
    end
  end

  test do
    system "#{bin}/rekord", "version"
  end
end
