# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rekord < Formula
  desc "Record terminal workflows as structured session data"
  homepage "https://github.com/Omotolani98/rekord"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.7/rekord_0.1.7_darwin_amd64.tar.gz"
      sha256 "0a2ffb632f73a60c52eaf710a933fb718d4d4e1be39ea7ff067fdf165cfa6345"

      define_method(:install) do
        bin.install "rekord"
        bin.install "rk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.7/rekord_0.1.7_darwin_arm64.tar.gz"
      sha256 "54e5e93f435da2248f9d5dc740ff528dee58411ae33a466bc608f7aa11c05471"

      define_method(:install) do
        bin.install "rekord"
        bin.install "rk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.7/rekord_0.1.7_linux_amd64.tar.gz"
      sha256 "e1ad53c28ef70d849ef63772f2f73df268213d329110dccc07edd2887833ae07"
      define_method(:install) do
        bin.install "rekord"
        bin.install "rk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.7/rekord_0.1.7_linux_arm64.tar.gz"
      sha256 "d604e6dc875871df3fb1227168fc80bb4889d3d51749c9a3e48885ae36d24256"
      define_method(:install) do
        bin.install "rekord"
        bin.install "rk"
      end
    end
  end

  test do
    system "#{bin}/rekord", "version"
    system "#{bin}/rk", "version"
  end
end
