# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rekord < Formula
  desc "Record terminal workflows as structured session data"
  homepage "https://github.com/Omotolani98/rekord"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.3/rekord_0.1.3_darwin_amd64.tar.gz"
      sha256 "49f83cf9610459b76f49f06c56b2c9b80fd66631e324ac422a60238645001959"

      define_method(:install) do
        bin.install "rekord"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.3/rekord_0.1.3_darwin_arm64.tar.gz"
      sha256 "b2b003b1d04cc70e2d68b0e98acf4862087ce0567bab3a738729898ca838a364"

      define_method(:install) do
        bin.install "rekord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.3/rekord_0.1.3_linux_amd64.tar.gz"
      sha256 "ad15ae5a7541132fdd04f7688667c60ea38cf2a527c4ed6d4373917391fc1b19"
      define_method(:install) do
        bin.install "rekord"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Omotolani98/rekord/releases/download/v0.1.3/rekord_0.1.3_linux_arm64.tar.gz"
      sha256 "5aeefec1ffb8e307fb55b7be81964f64ba86978d766187a6d0839ce5fba923b4"
      define_method(:install) do
        bin.install "rekord"
      end
    end
  end

  test do
    system "#{bin}/rekord", "version"
  end
end
